
#!/usr/bin/env python
"""
plot_counts.py
----------------
Plots a histogram of word frequencies from a CSV file generated by count_words.py using matplotlib.
Usage:
    python plot_counts.py <input-file> <output-file> [limit]
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt

def plot_word_counts(df: pd.DataFrame, limit: int = 10) -> None:
    """
    Plot a histogram of word counts from a pandas DataFrame.

    Args:
        df (pd.DataFrame): DataFrame with columns 'word' and 'count'.
        limit (int): Number of top words to plot.
    """
    limited_df = df.head(limit)
    position = range(len(limited_df))
    plt.figure(figsize=(6, 4))
    plt.bar(position, limited_df['count'], width=0.8)
    plt.xticks(position, limited_df['word'].tolist(), rotation=45, ha='right')
    plt.title("Word Counts")
    plt.ylabel("Counts")
    plt.xlabel("Word")
    plt.tight_layout()

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python plot_counts.py <input-file> <output-file> [limit]")
        sys.exit(1)
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    limit = int(sys.argv[3]) if len(sys.argv) > 3 else 10
    df = pd.read_csv(input_file)
    plot_word_counts(df, limit)
    if output_file == "show":
        plt.show()
    else:
        plt.savefig(output_file)
